
server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.100.234.80:36020/phorcys-centre?useSSL=false
          username: root
          password: H@ndAdmin
        interface:
          url: jdbc:mysql://39.100.234.80:36020/phorcys-interface?useSSL=false
          username: root
          password: H@ndAdmin
          driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID

phorcys:
  redis:
    host: 39.100.234.80
    port: 6379
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000

